### ISSUE TITLE
It doesn't work (anymore?)

### ISSUE THREAD

**Issue by neodraig** [TwinNet/Synology-ZippyShare-Host#1]
Hello,
I tried to download files from Zippyshare with download station on my Synology, but it doesn't work as it only download a few kilobytes instead of several hundred Mb.
I tried your host file but it didn't work. It might not be compatible anymore as it is 2 years old.
Is it fixable?
Thanks.

**Comment by simonabler** [comment]
Hi, 
Just tried it, it seems to work properly on my synology. 

Can you give me an example? Best the url.

**Comment by houps** [comment]
Hi,

I had the same problem (for example with https://www63.zippyshare.com/v/iYQ68JUx/file.html ).
I solved it by replacing 'Zippyshare.com - ' with 'Zippyshare.com', in the file host.php, line 116.
Your plugin is great!! Thanks for the job.

Chris
